var hunCities = [
    {
        "city": "Budapest", 
        "admin": "Budapest", 
        "country": "Hungary", 
        "population_proper": "1679000", 
        "iso2": "HU", 
        "capital": "primary", 
        "lat": "47.4979", 
        "lng": "19.0402", 
        "population": "1679000"
    }, 
    {
        "city": "Miskolc", 
        "admin": "Miskolc", 
        "country": "Hungary", 
        "population_proper": "172637", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "48.103478", 
        "lng": "20.778438", 
        "population": "247757"
    }, 
    {
        "city": "Debrecen", 
        "admin": "Debrecen", 
        "country": "Hungary", 
        "population_proper": "204124", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.531605", 
        "lng": "21.627312", 
        "population": "231286"
    }, 
    {
        "city": "Szeged", 
        "admin": "Szeged", 
        "country": "Hungary", 
        "population_proper": "164883", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.25301", 
        "lng": "20.141425", 
        "population": "187765"
    }, 
    {
        "city": "P\u00e9cs", 
        "admin": "P\u00e9cs", 
        "country": "Hungary", 
        "population_proper": "156649", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.0727345", 
        "lng": "18.232266", 
        "population": "186262"
    }, 
    {
        "city": "Ny\u00edregyh\u00e1za", 
        "admin": "Szabolcs-Szatm\u00e1r-Bereg", 
        "country": "Hungary", 
        "population_proper": "116298", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.9495324", 
        "lng": "21.7244053", 
        "population": "176880"
    }, 
    {
        "city": "Sz\u00e9kesfeh\u00e9rv\u00e1r", 
        "admin": "Fej\u00e9r", 
        "country": "Hungary", 
        "population_proper": "101600", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.1860", 
        "lng": "18.4221", 
        "population": "144319"
    }, 
    {
        "city": "Gy\u0151r", 
        "admin": "Gy\u0151r", 
        "country": "Hungary", 
        "population_proper": "128265", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.6874569", 
        "lng": "17.6503974", 
        "population": "136081"
    }, 
    {
        "city": "Kecskem\u00e9t", 
        "admin": "B\u00e1cs-Kiskun", 
        "country": "Hungary", 
        "population_proper": "109847", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.8964", 
        "lng": "19.6897", 
        "population": "113895"
    }, 
    {
        "city": "Szombathely", 
        "admin": "Vas", 
        "country": "Hungary", 
        "population_proper": "79534", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.2307", 
        "lng": "16.6218", 
        "population": "109518"
    }, 
    {
        "city": "Szolnok", 
        "admin": "J\u00e1sz-Nagykun-Szolnok", 
        "country": "Hungary", 
        "population_proper": "75474", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.1621", 
        "lng": "20.1825", 
        "population": "109261"
    }, 
    {
        "city": "Kaposv\u00e1r", 
        "admin": "Somogy", 
        "country": "Hungary", 
        "population_proper": "67746", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.3594", 
        "lng": "17.7968", 
        "population": "108528"
    }, 
    {
        "city": "B\u00e9k\u00e9scsaba", 
        "admin": "B\u00e9k\u00e9s", 
        "country": "Hungary", 
        "population_proper": "65206", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.6736", 
        "lng": "21.0877", 
        "population": "65206"
    }, 
    {
        "city": "Veszpr\u00e9m", 
        "admin": "Veszpr\u00e9m", 
        "country": "Hungary", 
        "population_proper": "62023", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.0931", 
        "lng": "17.9101", 
        "population": "62023"
    }, 
    {
        "city": "Zalaegerszeg", 
        "admin": "Zala", 
        "country": "Hungary", 
        "population_proper": "61898", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.8417", 
        "lng": "16.8416", 
        "population": "61898"
    }, 
    {
        "city": "Salg\u00f3tarj\u00e1n", 
        "admin": "N\u00f3gr\u00e1d", 
        "country": "Hungary", 
        "population_proper": "39640", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "48.0935", 
        "lng": "19.8000", 
        "population": "39640"
    }, 
    {
        "city": "V\u00e1c", 
        "admin": "Pest", 
        "country": "Hungary", 
        "population_proper": "35108", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "47.7842", 
        "lng": "19.1352", 
        "population": "35293"
    }, 
    {
        "city": "Szeksz\u00e1rd", 
        "admin": "Tolna", 
        "country": "Hungary", 
        "population_proper": "34174", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "46.3474", 
        "lng": "18.7062", 
        "population": "34174"
    },  
    {
        "city": "Tokaj", 
        "admin": "Borsod-Aba\u00faj-Zempl\u00e9n", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "48.1172", 
        "lng": "21.4089", 
        "population": ""
    }, 
    {
        "city": "Baja", 
        "admin": "B\u00e1cs-Kiskun", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.1818", 
        "lng": "18.9543", 
        "population": ""
    },
    {
        "city": "Szigetv\u00e1r", 
        "admin": "Baranya", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.0488", 
        "lng": "17.7983", 
        "population": ""
    }, 
    {
        "city": "Szarvas", 
        "admin": "B\u00e9k\u00e9s", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.8636", 
        "lng": "20.5527", 
        "population": ""
    }, 
    {
        "city": "Sopron", 
        "admin": "Gy\u0151r-Moson-Sopron", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.6817", 
        "lng": "16.5845", 
        "population": ""
    }, 
    {
        "city": "Moh\u00e1cs", 
        "admin": "Baranya", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.0046", 
        "lng": "18.6794", 
        "population": ""
    }, 
    {
        "city": "Si\u00f3fok", 
        "admin": "Somogy", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.9091", 
        "lng": "18.0746", 
        "population": ""
    }, 
    {
        "city": "Tatab\u00e1nya", 
        "admin": "Kom\u00e1rom-Esztergom", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.5692", 
        "lng": "18.4048", 
        "population": ""
    }, 
    {
        "city": "Balatonf\u00fcred", 
        "admin": "Veszpr\u00e9m", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.9599", 
        "lng": "17.8851", 
        "population": ""
    }, 
    {
        "city": "Gyomaendr\u0151d", 
        "admin": "B\u00e9k\u00e9s", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.9318", 
        "lng": "20.8113", 
        "population": ""
    }, 
    {
        "city": "Gyula", 
        "admin": "B\u00e9k\u00e9s", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.6473", 
        "lng": "21.2784", 
        "population": ""
    },
    {
        "city": "Eger", 
        "admin": "Heves", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "admin", 
        "lat": "47.9025", 
        "lng": "20.3772", 
        "population": ""
    }, 
    {
        "city": "Esztergom", 
        "admin": "Kom\u00e1rom-Esztergom", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "47.7884", 
        "lng": "18.7434", 
        "population": ""
    }, 
    {
        "city": "Keszthely", 
        "admin": "Zala", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.7655", 
        "lng": "17.2480", 
        "population": ""
    }, 
    {
        "city": "Kalocsa", 
        "admin": "B\u00e1cs-Kiskun", 
        "country": "Hungary", 
        "population_proper": "", 
        "iso2": "HU", 
        "capital": "minor", 
        "lat": "46.5281", 
        "lng": "18.9840", 
        "population": ""
    }
]
;